[project]
name = "eidolon"
version = "0.1.0"
description = "Infinite embeddeing memory for LLMs"
authors = [
    {name = "mathisto"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sentence-transformers (>=3.3.1,<4.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "fastapi (>=0.115.6,<0.116.0)",
    "llm (>=0.19.1,<0.20.0)",
    "openai (>=0.19.1)",
    "psycopg2 (>=2.9.10,<3.0.0)",
    "prompt-toolkit (>=3.0.48,<4.0.0)",
]

[tool.poetry]
packages = [
    { include = "eidolon" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
